# Site settings
title: GDG Xi'an
email: your-email@domain.com
description: "GDG Xi'an 是西安一家专注于 Google 技术和开源技术的社区, 欢迎各类朋友加入到 GDG Xi'an 的集体中来。"
baseurl: ""
url: "http://gdgxian.org"
paginate: 10
excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown
permalink: pretty

# Comments
disqus_short_name: gdgxian

plugins:
  - jekyll-paginate
  - jekyll-feed
